// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type InviteCode struct {
	UserID     int32
	InviteCode string
}

type User struct {
	ID        int32
	Username  string
	Password  string
	InviterID int32
}

type UserToken struct {
	UserID      int32
	AccessToken sql.NullString
}
